version: '3.8'

services:
  homezone-api:
    container_name: homezone-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4001:3007'
    environment:
      - NODE_ENV=production
    networks:
      - monorepo_network
    depends_on:
      - homezone-batch
    command: ['pnpm', 'run', 'start:prod']

  homezone-batch:
    container_name: homezone-batch
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4002:3008'
    environment:
      - NODE_ENV=production
    networks:
      - monorepo_network
    command: ['pnpm', 'run', 'start:prod:batch']

networks:
  monorepo_network:
    driver: bridge
