version: '3.8'

services:
  homezone-api:
    container_name: homezone-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3007:3007'
    environment:
      - NODE_ENV=production
    networks:
      - monorepo_network
      - web
    depends_on:
      - homezone-batch
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homezone-api.rule=Host(`admin.uomostore.shop`)'
      - 'traefik.http.routers.homezone-api.entrypoints=websecure'
      - 'traefik.http.routers.homezone-api.tls.certresolver=cloudflare'
      - 'traefik.http.services.homezone-api.loadbalancer.server.port=3007'
    command: ['pnpm', 'run', 'start:prod']

  homezone-batch:
    container_name: homezone-batch
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3008:3008'
    environment:
      - NODE_ENV=production
    networks:
      - monorepo_network
    command: ['pnpm', 'run', 'start:prod:batch']

networks:
  monorepo_network:
    driver: bridge
  web:
    external: true
